version: '3.1'
services:
  api:
    image: gnschenker/ddev-api:1.0
    ports:
      - 8080:8080
    depends_on:
      - database
    secrets:
      - postgres_password
    networks:
      - back-tier
  
  database:
    image: gnschenker/ddev-db:1.0
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: ddev
    secrets:
      - postgres_password
    networks:
      - back-tier

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password

networks:
  back-tier: